name: Deploy to storage container

on:
  push:
    branches:
      - 'master'

env:
  PACKAGE_PATH: '.'
  NODE_VERSION: '20.x'
  BASE_URL: /k4/

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using NPM'
        shell: bash
        run: |
          pushd './${{ env.PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          popd
        env:
          APP_BASE_API_URL: ${{ env.APP_BASE_API_URL}}
          BASE_URL: ${{ env.BASE_URL }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name sikosoftstorage --auth-mode key -d '$web/k4' -s '${{ env.PACKAGE_PATH }}/dist' --overwrite

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/k4/*" --profile-name "sikosoft" --name "sikosoft" --resource-group "SS"

      - name: logout
        run: |
          az logout
        if: always()
